### ISSUE TITLE
KeyError: 'minimizedAffinity' in tests 

### ISSUE THREAD

**Issue by youngh81** [mattragoza/LiGAN#64]
Hi, thanks for sharing. However, when I use ptest tests: 4 failed with flowing message:

FAILED tests/test_data.py::TestMolDataset::test_benchmark[False] - ValueError: Could not read data/crossdock2020/1A02_HUMAN_25_199_pep_0/1t1z_A_rec.pdb
FAILED tests/test_data.py::TestMolDataset::test_benchmark[True] - AssertionError: file does not exist
FAILED tests/test_generating.py::TestGenerator::test_generate[data/test_pockets/AROK_MYCTU_1_176_0/fixed_input_1zyu_A_rec_mutants.types] - KeyError: 'minimizedAffinity'
FAILED tests/test_generating.py::TestGenerator::test_generate[data/test_pockets/AROK_MYCTU_1_176_0/fixed_cond_1zyu_A_rec_mutants.types] - KeyError: 'minimizedAffinity'

What should I do for this? Thanks very much.

**Comment by mattragoza** [comment]
If you scroll up in the output, there will be a section delimited by `GNINA STDERR .... END GNINA STDERR`. Do you notice an error from gnina?

**Comment by youngh81** [comment]
Do you mean this message? But I think this could come from obabel.

GNINA STDERR
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders

terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN Error (out of memory?): CUDNN_STATUS_EXECUTION_FAILED
*** Aborted at 1680601781 (unix time) try "date -d @1680601781" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e80000597d) received by PID 22909 (TID 0x7f1d9ccd0000) from PID 22909; stack trace: ***
    @     0x7f1dc3b6e520 (unknown)
    @     0x7f1dc3bc2a7c pthread_kill
    @     0x7f1dc3b6e476 raise
    @     0x7f1dc3b547f3 abort
    @     0x7f1dc3effbfe (unknown)
    @     0x7f1dc3f0b28c (unknown)
    @     0x7f1dc3f0b2f7 std::terminate()
    @     0x7f1dc3f0b558 __cxa_throw
    @           0xa66a24 caffe::CuDNNReLULayer<>::Forward_gpu()
    @           0x9e8b71 caffe::Net<>::ForwardFromTo()
    @           0x9e8c96 caffe::Net<>::Forward()
    @           0x7bc4d3 CNNScorer::score()
    @           0x75e35e get_cnn_info()
    @           0x762aa4 do_search()
    @           0x764e97 main_procedure()
    @           0x7657de threads_at_work()
    @           0x77d203 boost::_bi::list6<>::operator()<>()
    @           0xadfc94 thread_proxy
    @     0x7f1dc3bc0b43 (unknown)
    @     0x7f1dc3c52a00 (unknown)
    @                0x0 (unknown)

END GNINA STDERR

**Comment by mattragoza** [comment]
Yes. You can ignore the openbabel warning, but notice the error message after that:
```
CUDNN Error (out of memory?): CUDNN_STATUS_EXECUTION_FAILED
```
How did you install gnina? Are you running with a GPU enabled, if so how much GPU memory?

**Comment by youngh81** [comment]
OK, yes I also noticed that, I followed the instruction for installation of gnina. My memory is 22G. thanks.

**Comment by andressanchezr4** [comment]
> Yes. You can ignore the openbabel warning, but notice the error message after that:
> 
> ```
> CUDNN Error (out of memory?): CUDNN_STATUS_EXECUTION_FAILED
> ```
> 
> How did you install gnina? Are you running with a GPU enabled, if so how much GPU memory? 

same error here, after installing the enviroment according to your steps I try to run `python3 generate.py config/generate.config`  I get the following error (besides the GNINA STDERR): 

{'error': 'terminate called after throwing an instance of \'std::runtime_error\'\n  what():  CUDNN Error (out of memory?): CUDNN_STATUS_EXECUTION_FAILED\n*** Aborted at 1684396037 (unix time) try "date -d @1684396037" if you are using GNU date ***\nPC: @                0x0 (unknown)\n*** SIGABRT (@0x3e90019adbb) received by PID 1682875 (TID 0x7f896cd27000) from PID 1682875; stack trace: ***\n    @     0x7f89ac842520 (unknown)\n    @     0x7f89ac896a7c pthread_kill\n    @     0x7f89ac842476 raise\n    @     0x7f89ac8287f3 abort\n    @     0x7f89acca2bbe (unknown)\n    @     0x7f89accae24c (unknown)\n    @     0x7f89accae2b7 std::terminate()\n    @     0x7f89accae518 __cxa_throw\n    @           0xa66a24 caffe::CuDNNReLULayer<>::Forward_gpu()\n    @           0x9e8b71 caffe::Net<>::ForwardFromTo()\n    @           0x9e8c96 caffe::Net<>::Forward()\n    @           0x7bc4d3 CNNScorer::score()\n    @           0x75e35e get_cnn_info()\n    @           0x762aa4 do_search()\n    @           0x764e97 main_procedure()\n    @           0x7657de threads_at_work()\n    @           0x77d203 boost::_bi::list6<>::operator()<>()\n    @           0xadfc94 thread_proxy\n    @     0x7f89ac894b43 (unknown)\n    @     0x7f89ac926a00 (unknown)\n    @                0x0 (unknown)\n'}
Traceback (most recent call last):
  File "/home/andres/LiGAN/generate.py", line 45, in <module>
    main(sys.argv[1:])
  File "/home/andres/LiGAN/generate.py", line 40, in main
    generator.generate(**config['generate'])
  File "/home/andres/LiGAN/ligan/generating.py", line 566, in generate
    self.out_writer.write(
  File "/home/andres/LiGAN/ligan/generating.py", line 950, in write
    self.compute_metrics(example_info, sample_idx)
  File "/home/andres/LiGAN/ligan/generating.py", line 1169, in compute_metrics
    self.compute_mol_metrics(idx,
  File "/home/andres/LiGAN/ligan/generating.py", line 1486, in compute_mol_metrics
    ref_vina_aff = ref_gni_mol.info['minimizedAffinity']
KeyError: 'minimizedAffinity'

I have 24 Gb of memory, what do you think is going wrong? 

I also get the error of a non existing file as it seems that the data/crossdock2020/1A02_HUMAN_25_199_pep_0/1t1z_A_rec.pdb file is missing as I cannot find it where the path points, could it by any chance have been removed?

**Comment by mattragoza** [comment]
What system are you each running this on?

**Comment by kenndshi** [comment]
@mattragoza  I have the same errors.
I am running on Ubuntu 22.04
